### PR TITLE
Dep on menpo 0.6.0, assimp preprocess

### PR DESCRIPTION
**Pull request by jabooth**
Adds a new preprocess flag to import_mesh{es} that controls whether or not Assimp will perform mesh cleanup upon import.

Previously this was not user selectable and was on by default, which caused issues when it was desirable to load a mesh and not change the structure.

Note that this breaking change in behavior will mean a version jump for menpo3d.

### CODE REVIEW

**Comment by jabooth** [comment]
We're now blocked on moving forward with the new menpo3d release until we have access to a numpy 1.10 release of mayavi, see: https://github.com/ContinuumIO/anaconda-issues/issues/531

**Comment by patricksnape** [comment]
@jabooth We could make our own mayavi build? It's actually quite simple because `skeleton` correctly creates a conda build script. The hard part is VTK and the Continuum guys did that for us already!

**Comment by jabooth** [comment]
@patricksnape yeah we could! Another thing to maintain but if it's going to be a while I'd rather sort it than be in this awkward position where we can't release the full project

**Comment by jabooth** [comment]
I've setup http://github.com/menpo/conda-mayavi so we can move forward now

**Comment by jabooth** [comment]
@patricksnape going to merge this in now, and check the resulting master build has the cyassimp fixes correctly working. If so we are good for the menpo3d release.

**Pull request merged**
